typography_spectrum: 0.23258
color:
  brandColors:
    - '#ffffff'
    - '#f05536'
    - '#59585d'
    - '#6ecff0'
    - '#f99f25'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.92693
analytics:
  google: null
  facebook: null
  twitter: null
name: chelseydoyle
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Chelsey Doyle
description: communication design
purpose: []
