name: chelseydoyle
favicon: null
layout_spectrum: 0.6718060350976884
typography_spectrum: 0.9633198254741728
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8947653898503631
  lightness: 0.2204771670512855
  saturation: 0.9753294291440398
  rhythmicContrast: 0.20330146444030106
purpose: []
